DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS contest;
DROP TABLE IF EXISTS election;
DROP TABLE IF EXISTS candidate;
DROP TABLE IF EXISTS party;
DROP TABLE IF EXISTS precinct;
DROP TABLE IF EXISTS county;
DROP TABLE IF EXISTS state;
